// Generated by `npm run dump:entities -- --write` from the RC Together
// stream: field names and value kinds only. Do not edit by hand; regenerate
// and review the diff. A field is optional if some sampled entity lacked it.

export interface UpstreamAudioBlock {
  audio_room_id: number;
  color: string;
  id: number;
  mute_on_entry: boolean;
  name: null | string;
  pos: { x: number; y: number };
  type: "AudioBlock";
}

export interface UpstreamAudioRoom {
  expires_at: null;
  has_audio_block: boolean;
  height: number;
  id: number;
  mute_on_entry: boolean;
  pos: { x: number; y: number };
  type: "AudioRoom";
  width: number;
}

export interface UpstreamAvatar {
  direction: string;
  flair: null | string;
  id: number;
  image_path: string;
  last_idle_at: string;
  last_present_at: string;
  last_seen_at: string;
  message: null | {
    mentioned_entity_ids: Array<number>;
    sent_at: string;
    text: string;
  };
  muted: boolean;
  person_name: string;
  pos: { x: number; y: number };
  rc_hub_visit_notes: null | string;
  rc_hub_visit_today: boolean | null;
  type: "Avatar";
  updated_at: string;
  user_id: number;
  zoom_meeting_topic: null;
  zoom_user_display_name: null;
  zoom_user_id: null;
}

export interface UpstreamBot {
  app: { id: number; name: string };
  can_be_mentioned: boolean;
  direction: string;
  display_name: string;
  emoji: string;
  id: number;
  message: null | {
    mentioned_entity_ids: Array<number>;
    sent_at: string;
    text: string;
  };
  name: string;
  pos: { x: number; y: number };
  type: "Bot";
}

export interface UpstreamDesk {
  color: string;
  emoji: null | string;
  expires_at: null | string;
  id: number;
  owner?: { id: number; image_url: string; name: string };
  pos: { x: number; y: number };
  profile_url: null | string;
  status: null | string;
  type: "Desk";
}

export interface UpstreamLink {
  color: string;
  id: number;
  pos: { x: number; y: number };
  type: "Link";
  url: null | string;
}

export interface UpstreamNote {
  color: string;
  id: number;
  note_text: null | string;
  note_updated_at: null | string;
  pos: { x: number; y: number };
  type: "Note";
  updated_by?: { id: null | number; name: string };
}

export interface UpstreamPhotoBlock {
  color: string;
  id: number;
  photo_attached: boolean;
  pos: { x: number; y: number };
  type: "PhotoBlock";
}

export interface UpstreamRCCalendar {
  calendar_data: Array<{
    end_time: string;
    start_time: string;
    title: string;
    url: string;
  }>;
  color: string;
  id: number;
  pos: { x: number; y: number };
  type: "RC::Calendar";
  updated_at: string;
  zoom_user: { display_name: string; id: number };
}

export interface UpstreamWall {
  color: string;
  id: number;
  pos: { x: number; y: number };
  type: "Wall";
  wall_text: null | string;
}

export interface UpstreamZoomLink {
  color: string;
  id: number;
  participant_count: number;
  pos: { x: number; y: number };
  type: "ZoomLink";
  zoom_user?: { display_name: string; id: number };
}

export type UpstreamEntity =
  | UpstreamAudioBlock
  | UpstreamAudioRoom
  | UpstreamAvatar
  | UpstreamBot
  | UpstreamDesk
  | UpstreamLink
  | UpstreamNote
  | UpstreamPhotoBlock
  | UpstreamRCCalendar
  | UpstreamWall
  | UpstreamZoomLink;

/** Field names per entity type, for checking JSON fixtures at runtime. */
export const UPSTREAM_FIELDS = {
  AudioBlock: [
    "audio_room_id",
    "color",
    "id",
    "mute_on_entry",
    "name",
    "pos",
    "type",
  ],
  AudioRoom: [
    "expires_at",
    "has_audio_block",
    "height",
    "id",
    "mute_on_entry",
    "pos",
    "type",
    "width",
  ],
  Avatar: [
    "direction",
    "flair",
    "id",
    "image_path",
    "last_idle_at",
    "last_present_at",
    "last_seen_at",
    "message",
    "muted",
    "person_name",
    "pos",
    "rc_hub_visit_notes",
    "rc_hub_visit_today",
    "type",
    "updated_at",
    "user_id",
    "zoom_meeting_topic",
    "zoom_user_display_name",
    "zoom_user_id",
  ],
  Bot: [
    "app",
    "can_be_mentioned",
    "direction",
    "display_name",
    "emoji",
    "id",
    "message",
    "name",
    "pos",
    "type",
  ],
  Desk: [
    "color",
    "emoji",
    "expires_at",
    "id",
    "owner",
    "pos",
    "profile_url",
    "status",
    "type",
  ],
  Link: ["color", "id", "pos", "type", "url"],
  Note: [
    "color",
    "id",
    "note_text",
    "note_updated_at",
    "pos",
    "type",
    "updated_by",
  ],
  PhotoBlock: ["color", "id", "photo_attached", "pos", "type"],
  "RC::Calendar": [
    "calendar_data",
    "color",
    "id",
    "pos",
    "type",
    "updated_at",
    "zoom_user",
  ],
  Wall: ["color", "id", "pos", "type", "wall_text"],
  ZoomLink: ["color", "id", "participant_count", "pos", "type", "zoom_user"],
} as const satisfies Record<UpstreamEntity["type"], readonly string[]>;
